name             'application_go'
maintainer       'Granicus Inc.'
maintainer_email 'Nathan Holland <nathanh@granicus.com>'
license          'Apache v2.0'
description      'Application pattern for golang'
version          '0.1.0'
recipe           'go', 'Installs golang'
depends          'application', '>= 3.0.0'
depends          'golang'
